name: Training and education
slug: training-education
description: >-
  How does (digital) humanities-based research support, facilitate and
  contribute to training, education and continued professional development?
