import type { CmsCollection } from 'netlify-cms-core'

export const events: CmsCollection = {
  name: 'events',
  label: 'Events',
  label_singular: 'Event',
  description: 'Events',
  format: 'frontmatter',
  extension: 'mdx',
  create: true,
  delete: false,
  folder: 'content/events',
  media_folder: '../../{{media_folder}}/events/{{slug}}',
  public_folder: '{{public_folder}}/events/{{slug}}',
  slug: '{{slug}}',
  preview_path: 'resource/{{slug}}',
  editor: { preview: true },
  sortable_fields: ['commit_date', 'date', 'title', 'commit_author'],
  view_groups: [
    {
      label: 'Year',
      field: 'date',
      pattern: '\\d{4}',
    },
  ],
  fields: [
    {
      name: 'title',
      label: 'Title',
      hint: '',
    },
    {
      name: 'shortTitle',
      label: 'Short title',
      hint: '',
      required: false,
    },
    {
      name: 'eventType',
      label: 'Event type',
      hint: 'E.g. Winter School',
      required: false,
    },
    {
      name: 'lang',
      label: 'Language',
      hint: '',
      widget: 'select',
      options: [
        {
          label: 'English',
          value: 'en',
        },
        {
          label: 'Deutsch',
          value: 'de',
        },
      ],
      default: 'en',
    },
    {
      name: 'date',
      label: 'Date',
      hint: '',
      widget: 'datetime',
      date_format: 'DD/MM/YYYY',
      time_format: false,
      picker_utc: true,
      default: '',
    },
    {
      name: 'tags',
      label: 'Topics',
      hint: '',
      widget: 'relation',
      collection: 'tags',
      multiple: true,
      value_field: '{{slug}}',
      search_fields: ['name'],
      display_fields: ['name'],
    },
    {
      name: 'categories',
      label: 'Sources',
      // hint: '',
      // widget: 'relation',
      // collection: 'categories',
      // multiple: true,
      // value_field: '{{slug}}',
      // search_fields: ['name'],
      // display_fields: ['name'],
      default: ['events'],
      widget: 'hidden',
    },
    {
      name: 'logo',
      label: 'Logo',
      hint: '',
      required: false,
      widget: 'image',
    },
    {
      name: 'featuredImage',
      label: 'Featured image',
      hint: '',
      required: false,
      widget: 'image',
    },
    {
      name: 'abstract',
      label: 'Abstract',
      hint: 'Provide one or two sentences to briefly describe the event',
      widget: 'text',
    },
    {
      name: 'authors',
      label: 'Persons responsible for the event',
      hint: '',
      required: false,
      widget: 'relation',
      collection: 'people',
      multiple: true,
      value_field: '{{slug}}',
      search_fields: ['firstName', 'lastName'],
      display_fields: ['{{firstName}} {{lastName}}'],
    },
    {
      name: 'body',
      label: 'Short description',
      widget: 'markdown',
      editor_components: [],
      hint: '',
    },
    {
      name: 'about',
      label: 'About',
      widget: 'markdown',
      editor_components: ['image'],
      hint: '',
    },
    {
      name: 'prep',
      label: 'Preparation notes',
      widget: 'markdown',
      editor_components: ['image', 'code-block'],
      hint: '',
      required: false,
    },
    {
      name: 'type',
      label: 'Content type',
      // hint: 'This generates an icon, please select the most appropriate for your resource',
      // widget: 'relation',
      // collection: 'content-types',
      // value_field: '{{slug}}',
      // search_fields: ['name'],
      // display_fields: ['name'],
      default: 'event',
      widget: 'hidden',
    },
    {
      name: 'licence',
      label: 'Licence',
      hint: '',
      widget: 'relation',
      collection: 'licences',
      value_field: '{{slug}}',
      search_fields: ['name'],
      display_fields: ['name'],
      default: 'ccby-4.0',
    },
    {
      name: 'partners',
      label: 'Partner organisations',
      label_singular: 'Partner organisation',
      hint: '',
      required: false,
      // widget: 'list',
      // fields: [
      //   {
      //     name: 'name',
      //     label: 'Name',
      //     hint: '',
      //   },
      //   {
      //     name: 'logo',
      //     label: 'Logo',
      //     hint: '',
      //     required: false,
      //     widget: 'image',
      //   },
      //   {
      //     name: 'url',
      //     label: 'URL',
      //     hint: '',
      //     required: false,
      //     pattern: ['^[a-zA-Z][a-zA-Z\\d+\\-.]*:', 'Must be a valid URL'],
      //   },
      // ],
      widget: 'relation',
      collection: 'organisations',
      multiple: true,
      value_field: '{{slug}}',
      search_fields: ['name'],
      display_fields: ['name'],
    },
    {
      name: 'social',
      label: 'Social',
      hint: '',
      required: false,
      widget: 'object',
      collapsed: true,
      fields: [
        {
          name: 'website',
          label: 'Website',
          hint: '',
          required: false,
          pattern: ['^[a-zA-Z][a-zA-Z\\d+\\-.]*:', 'Must be a valid URL'],
        },
        {
          name: 'email',
          label: 'Email',
          hint: '',
          required: false,
          pattern: [
            '^[^\\.\\s@:](?:[^\\s@:]*[^\\s@:\\.])?@[^\\.\\s@]+(?:\\.[^\\.\\s@]+)*$',
            'Must be a valid Email address',
          ],
        },
        {
          name: 'twitter',
          label: 'Twitter handle',
          hint: '',
          required: false,
        },
        {
          name: 'flickr',
          label: 'Flickr',
          hint: '',
          required: false,
        },
      ],
    },
    {
      name: 'synthesis',
      label: 'Synthesis',
      hint: '',
      required: false,
      widget: 'file',
      media_folder:
        // '../../{{media_folder}}/../../documents/cms/events/{{slug}}',
        '../../public/assets/documents/cms/events/{{slug}}',
      public_folder:
        // '{{public_folder}}/../../documents/cms/events/{{slug}}',
        '/assets/documents/cms/events/{{slug}}',
    },
    {
      name: 'sessions',
      label: 'Event sessions',
      label_singular: 'Event session',
      hint: '',
      widget: 'list',
      min: 1,
      fields: [
        {
          name: 'title',
          label: 'Title',
          hint: '',
        },
        // {
        //   name: 'shortTitle',
        //   label: 'Short title',
        //   hint: '',
        //   required: false,
        // },
        {
          name: 'speakers',
          label: 'Speakers',
          hint: '',
          widget: 'relation',
          collection: 'people',
          multiple: true,
          value_field: '{{slug}}',
          search_fields: ['firstName', 'lastName'],
          display_fields: ['{{firstName}} {{lastName}}'],
        },
        {
          name: 'body',
          label: 'Content',
          hint: '',
          widget: 'markdown',
          editor_components: [
            'image',
            'code_block',
            'Video',
            'EventSessionSpeakers',
            'EventSessionDownload',
            'EventSessionLink',
          ],
        },
        {
          name: 'synthesis',
          label: 'Synthesis',
          hint: '',
          required: false,
          widget: 'file',
          media_folder:
            // '../../{{media_folder}}/../../documents/cms/events/{{slug}}',
            '../../public/assets/documents/cms/events/{{slug}}',
          public_folder:
            // '{{public_folder}}/../../documents/cms/events/{{slug}}',
            '/assets/documents/cms/events/{{slug}}',
        },
      ],
    },
  ],
}
