import type { CmsCollection } from 'netlify-cms-core'

export const resourceCollections: CmsCollection = {
  name: 'resourceCollections',
  label: 'Curricula',
  label_singular: 'Curriculum',
  description: 'Collections of resources',
  format: 'frontmatter',
  extension: 'mdx',
  create: true,
  delete: false,
  folder: 'content/curricula',
  media_folder: '../../{{media_folder}}/curricula/{{slug}}',
  public_folder: '{{public_folder}}/curricula/{{slug}}',
  slug: '{{slug}}',
  preview_path: 'curriculum/{{slug}}',
  editor: { preview: true },
  sortable_fields: ['commit_date', 'date', 'title', 'commit_author'],
  view_groups: [
    {
      label: 'Year',
      field: 'date',
      pattern: '\\d{4}',
    },
  ],
  fields: [
    {
      name: 'title',
      label: 'Title',
      hint: 'Title of your resource',
    },
    {
      name: 'shortTitle',
      label: 'Short title',
      required: false,
      hint: 'Used in overview page',
    },
    {
      name: 'date',
      label: 'Date',
      hint: 'Date the resource was published on DARIAH-Campus',
      widget: 'datetime',
      date_format: 'DD/MM/YYYY',
      time_format: false,
      picker_utc: true,
      default: '',
    },
    {
      name: 'resources',
      label: 'Resources',
      label_singular: 'Resource',
      hint: 'Resources contained in this collection',
      widget: 'list',
      collapsed: false,
      minimize_collapsed: false,
      summary: '{{fields.post}}',
      min: 1,
      field: {
        name: 'post',
        label: 'Resource',
        widget: 'relation',
        collection: 'resources',
        value_field: '{{slug}}',
        search_fields: ['title'],
        display_fields: ['title'],
      },
    },
    {
      name: 'abstract',
      label: 'Abstract',
      hint: 'Provide one or two sentences to briefly describe the curriculum',
      widget: 'text',
    },
    {
      name: 'body',
      label: 'Content',
      hint: 'Description of the collection',
      widget: 'markdown',
      editor_components: ['image', 'code-block', 'Grid', 'SideNote', 'Video'],
    },
  ],
}
